[pytest]
asyncio_mode = auto
filterwarnings =
    ignore::pydantic.PydanticDeprecatedSince20
    ignore::pytest.PytestRemovedIn9Warning
    ignore::DeprecationWarning:google.protobuf.*
    ignore::DeprecationWarning:google.genai.*
    ignore::PendingDeprecationWarning:starlette.*
    ignore::ResourceWarning:anyio.*
    ignore::ResourceWarning:httpx.*
    ignore::DeprecationWarning:google._upb.*
    ignore::DeprecationWarning:importlib._bootstrap
