"""
Data models for the Event Concierge platform.
Enforces strict validation and schema integrity for Attendee and Staff flows.
"""
from datetime import datetime
from typing import Annotated, List, Optional
from pydantic import BaseModel, ConfigDict, Field, StringConstraints, model_validator

class Coordinates(BaseModel):
    """Geographic coordinates for spatial grounding."""
    model_config = ConfigDict(populate_by_name=True, frozen=True)

    latitude: float = Field(..., ge=-90, le=90, description="Latitude of the location")
    longitude: float = Field(..., ge=-180, le=180, description="Longitude of the location")

class UserConstraints(BaseModel):
    """Input constraints for agentic itinerary generation."""
    model_config = ConfigDict(populate_by_name=True, frozen=True)

    user_location: Coordinates = Field(..., description="The attendee's current spatial origin")
    start_time: str = Field(..., pattern=r"^\d{1,2}:\d{2} [AP]M$", description="Itinerary start window (e.g. 10:00 AM)")
    end_time: str = Field(..., pattern=r"^\d{1,2}:\d{2} [AP]M$", description="Itinerary end window (e.g. 05:00 PM)")
    preferred_topics: List[Annotated[str, StringConstraints(min_length=2, max_length=50)]] = Field(
        ..., min_length=1, description="Topical interests for event filtering"
    )

    @model_validator(mode='after')
    def validate_time_sequence(self) -> 'UserConstraints':
        """Ensures the chronological integrity of the event window."""
        fmt = "%I:%M %p"
        try:
            start = datetime.strptime(self.start_time, fmt)
            end = datetime.strptime(self.end_time, fmt)
            if start >= end:
                raise ValueError("The start_time must be chronologically before the end_time.")
        except ValueError as e:
            if "start_time" in str(e):
                raise e
            raise ValueError(f"Invalid time format. Expected 'HH:MM AM/PM', got '{self.start_time}' or '{self.end_time}'")
        return self

class Event(BaseModel):
    """Representation of a conference event with spatial transition data."""
    model_config = ConfigDict(populate_by_name=True, frozen=True)

    event_name: str = Field(..., description="Canonical name of the event")
    start_time: str = Field(..., description="Formatted event start time")
    end_time: str = Field(..., description="Formatted event end time")
    walking_directions: str = Field(..., description="Pathfinding narration between venues")
    transition_time_seconds: int = Field(..., ge=0, description="Allocated walking buffer in seconds")

class ItineraryResponse(BaseModel):
    """The final AI-orchestrated attendee schedule."""
    model_config = ConfigDict(populate_by_name=True)

    current_weather: Optional[str] = Field(default=None, description="Metereological context for navigation")
    itinerary: List[Event] = Field(..., description="Chronological, conflict-free event sequence")
    simulated: bool = Field(default=False, description="Indicator for deterministic fallback results")

class StaffActionRequest(BaseModel):
    """Tactical alert request from venue sensors or staff interface."""
    model_config = ConfigDict(populate_by_name=True, frozen=True)

    zone_id: str = Field(..., description="Target zone identifier (e.g. 'Zone B')")
    alert_type: str = Field(..., description="Metric driving the tactical deployment (e.g. 'Crowd Density')")

class StaffActionResponse(BaseModel):
    """Tactical protocol generated by the orchestration engine."""
    model_config = ConfigDict(populate_by_name=True)

    protocol: str = Field(..., description="Narrated personnel deployment instructions")
    simulated: bool = Field(default=False, description="Indicator for deterministic fallback results")

